on:
  pull_request:
    paths-ignore:
      - "**.md"

name: CI
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: test
        run: npm test --watchAll=false
